authentication/urls.py
from django.urls import path
from .views import login_page, register_page, redirect_to_login, logout_page

urlpatterns = [
    path("", redirect_to_login),
    path("login/", login_page, name="login"),
    path("register/", register_page, name="register"),
    path("logout/", logout_page, name="logout"),
]

dashboard/urls.py
from django.urls import path
from .views import Dashboard, issue_page, ReportPage, search_page

urlpatterns = [
    path("", Dashboard.as_view(), name="dashboard"),
    path("issue/<int:pk>", issue_page, name="issue"),
    path("report/", ReportPage.as_view(), name="report"),
    path("search/", search_page, name="search"),
]

issue_tracking_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('dashboard.urls')),
]

authentication/models.py
from django.contrib.auth import get_user_model
from django.db import models

dashboard/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_quill.fields import QuillField

User = get_user_model()


class Issue(models.Model):
    PRIORITY_CHOICES = (
        (0, "Information"),
        (1, "Warning"),
        (2, "Error"),
        (3, "Critical"),
    )

    STATUS_CHOICES = (
        (0, "Pending"),
        (1, "In progress"),
        (2, "Suspend"),
        (3, "Completed"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120, verbose_name="Название")
    text = QuillField(verbose_name="Описание")
    git = models.URLField(blank=True, null=True)
    date_time = models.DateTimeField(auto_now_add=True)
    priority = models.IntegerField(choices=PRIORITY_CHOICES, blank=True, null=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-date_time',)


class Message(models.Model):
    text = models.TextField(verbose_name="Сообщение")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

dashboard/forms.py
from django import forms

from dashboard.models import Message, Issue


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('text',)


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = "__all__"
        exclude = ("priority", "user", "status")


class StaffEditIssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ("priority", "status")

authentication/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


def login_page(request):
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)

            next_page = request.GET.get('next', None)

            if next_page:
                return redirect(next_page)
            else:
                return redirect("dashboard")

    context = {
        "form": form,
    }

    return render(request, 'authentication/login.html', context)


def register_page(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            form.save()

            return redirect('login')

    context = {
        "form": form,
    }

    return render(request, 'authentication/register.html', context)


def redirect_to_login(request):
    return redirect("login")


def logout_page(request):
    logout(request)
    return redirect('login')

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView

from .forms import IssueForm
from .models import Issue
from .services import get_issue, get_form, get_staff_from


class Dashboard(LoginRequiredMixin, ListView):
    template_name = "dashboard/dashboard.html"
    model = Issue
    login_url = reverse_lazy("login")

    def get_queryset(self):
        if self.request.user.is_staff:
            return self.model.objects.all()
        return self.model.objects.filter(user=self.request.user)


def search_page(request):
    username = request.GET.get("username", None)
    if username:
        users = User.objects.filter(username__contains=username)
        issue_list = Issue.objects.filter(user__in=users)
        context = {
            "issue_list": issue_list,
        }
    else:
        context = {}

    return render(request, "dashboard/dashboard.html", context)


def issue_page(request, pk):
    issue = get_issue(pk)
    form = get_form(request, issue)

    if request.user.is_staff:
        staff_form = get_staff_from(request.POST, issue)
    else:
        staff_form = None

    if issue.user == request.user or request.user.is_staff:
        if not issue:
            return HttpResponseNotFound()

        context = {
            "issue": issue,
            "form": form,
            "staff_form": staff_form,
        }

        return render(request, 'dashboard/issue.html', context)

    return HttpResponseForbidden()


class ReportPage(FormView):
    template_name = 'dashboard/report.html'
    form_class = IssueForm
    success_url = reverse_lazy("dashboard")

    def form_valid(self, form):
        issue = form.save(commit=False)
        issue.user = self.request.user
        issue.save()

        return super().form_valid(form)

authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Авторизация
{% endblock %}


{% block body %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 card p-5">
                <h1>Авторизация</h1>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex">
                        <button class="btn btn-primary w-100 mr-1" type="submit">Войти</button>
                        <a class="btn btn-secondary w-100 ml-1" href="{% url 'register' %}" type="submit">Регстрация</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

authentication/templates/authentication/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Регистрация
{% endblock %}


{% block body %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 card p-5">
                <h1>Регистрация</h1>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex">
                        <button class="btn btn-primary w-100 mr-1" type="submit">Зарегистрироваться</button>
                        <a class="btn btn-secondary w-100 ml-1" href="{% url 'login' %}" type="submit">Вход</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends 'site.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form method="get" class="py-5" action="{% url "search" %}">
                    <div class="form-group">
                        <label for="username">Имя пользователя</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <button class="btn btn-secondary" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </div>
    <div class="container mt-5">
        <div class="row row-cols-1 row-cols-md-2">
            {% for issue in issue_list %}
                <div class="col mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ issue.title }}</h5>
                            {% if request.user.is_staff %}
                                <p class="text-muted">{{ issue.user }}</p>
                            {% endif %}
                            <p class="card-text">{{ issue.text.html|striptags|truncatewords:20 }}</p>
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                            <span>{{ issue.get_status_display }}</span>
                            <span>{{ issue.date_time }}</span>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'issue' issue.pk %}" class="btn btn-primary btn-block">Открыть</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/issue.html
{% extends 'site.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Issue
{% endblock %}


{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <h2>{{ issue.title }}</h2>
                <div class="d-flex justify-content-between my-3 text-muted">
                    <p>Reporter: {{ issue.user }}</p>
                    <p>Status: {{ issue.get_status_display }}</p>
                    <p>Date & time: {{ issue.date_time }}</p>
                </div>
                {% autoescape off %}
                    <p>{{ issue.text.html }}</p>
                {% endautoescape %}
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">

            <div class="col-12">
                <hr class="my-5">
                {% for message in issue.message_set.all %}
                    <div class="mb-4 card p-4">
                        <p class="font-weight-bolder">{{ message.user }}</p>
                        <p>{{ message.text }}</p>
                        <p class="text-muted">{{ message.date_time }}</p>
                    </div>
                {% empty %}
                    <h4 class="text-muted text-center">Пока сообщений нет</h4>
                {% endfor %}
            </div>
        </div>
        {% if issue.status < 2 %}
            <div class="row">
                <div class="col-12">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        {% if request.user.is_staff %}
                            {{ staff_form|crispy }}
                        {% endif %}
                        <input type="submit" class="btn btn-primary btn-block mt-3" value="Отправить">
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

dashboard/templates/dashboard/report.html
{% extends 'site.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Сообщить о пролеме
{% endblock %}


{% block content %}
    {{ form.media }}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1>Сообщить о пролеме</h1>
                <form method="post" class="mt-4">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary btn-block mt-4">Сообщить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include 'django_quill/media.html' %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Issue system | {% block title %}Title{% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
<style>
    pre {
        background: #555;
        color: #fff;
        padding: 25px;
        border-radius: 5px;
    }
</style>
</html>

templates/site.html
{% extends 'base.html' %}

{% block body %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'dashboard' %}">ISystem</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'dashboard' %}">Все проблемы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'report' %}">Сообщить о проблеме</a>
                    </li>
                </ul>
                <span class="navbar-text">
            С возвращением, {{ request.user }}! [<a href="{% url 'logout' %}">Выйти</a>]
            </span>
            </div>
        </div>
    </nav>
    
    {% block content %}
    
    {% endblock %}
{% endblock %}